### ISSUE TITLE
cloudant package : create and delete trigger should should verify creation or deletion

### ISSUE THREAD

**Issue by RSulzmann** [apache/incubator-openwhisk-package-cloudant#122]
https://github.com/apache/incubator-openwhisk-package-cloudant/blob/master/actions/changesWebAction.js
The functions **createTrigger** and **deleteTrigger** should guarantee on return, that the trigger is created or deleted.

Our test code based on this package cannot check the existence of the trigger and we get sometimes errors when the creation or deletion is processed delayed.

**Comment by jasonpet** [comment]
We cannot make this guarantee in the current design.  The changesWebAction only creates/deletes the database entry and has not contact with the backend provider.  The trigger feed gets created by the backend provider when it is notified by a cloudant changes feed that a database entry has been created or deleted.

**Comment by mdeuser** [comment]
@jasonpet - is there a state in that db record that indicates the feed has been actually created?
