### ISSUE TITLE
Possible bug around empty query_params when filter is present

### ISSUE THREAD

**Issue by eweiter** [apache/incubator-openwhisk-package-cloudant#165]
This issue has two parts:
1) It was discovered that when trying to create a Cloudant Trigger if one specifies a "filter" but leaves the "query_params" blank the server will return an error complaining that the "query_params" are not valid JSON. 

I believe this happened after the recent fix for validating the "query_params" to be correct JSON. 

From glancing at the code it appears the fix would possibly be to add an extra condition to check for undefined query params and to allow them through when the filter is specified. 

2) A user was reporting that when they would supply `{}` as their "query_param" (so that they could get past the Invalid JSON error) the filter will no longer fire on their Trigger.

**Comment by csantanapr** [comment]
@eweiter 
>recent fix for validating the "query_params" to be correct JSON.

Can you point to a PR or commit in this repo that you are referring to this?

>when they would supply {} as their "query_param"

I would consider this user/client error, as if there is no parameters the `query_param` should be specified.
I guess we could take a look at improving the validation of `query_param` to make sure is a JSON object and that is not empty.

Do you have a series of steps using the CLI to reproduce the error so we are clear what are you doing to see this problem?

@jasonpet Could you take a look at this when you have a chance.

**Comment by eweiter** [comment]
@csantanapr 
This is the PR: https://github.com/apache/incubator-openwhisk-package-cloudant/pull/164/files
The user said that they used to create their trigger simply with 
`bx wsk trigger create <trigger-name> --feed /$IBMCLOUD_ORG_$space/<db-binding>/changes -p dbname <db> -p filter document-updates/new`
But now the server returns an error "Invalid JSON for query_params" so they started including the `{}` and their filter doesn't work. 

That is the extent that I know.  Jason and I have spoken and he is picking it up to see if we have an issue here.

**Comment by jasonpet** [comment]
looks like a regression due to PR 164.  query_params should not be required.

**Comment by jasonpet** [comment]
@csantanapr - this can be closed.  PR #166 fixed this.
