### ISSUE TITLE
Support IAM keys for Cloudant instances

### ISSUE THREAD

**Issue by jthomas** [apache/incubator-openwhisk-package-cloudant#193]
The [source code](https://github.com/apache/incubator-openwhisk-package-cloudant/blob/master/provider/app.js#L52) for the provider uses Basic auth to provide the username and password to the Cloudant instance. 

```
var cloudant = require('@cloudant/cloudant')(dbProtocol + '://' + dbUsername + ':' + dbPassword + '@' + dbHost);
```

Newer service keys for Cloudant now default to using IAM-based authentication....

```
var cloudant = new Cloudant({ url: 'https://examples.cloudant.com', plugins: { iamauth: { iamApiKey: 'xxxxxxxxxx' } } });
```

The provider should support both options for authentication based on whether the username and password or IAM API key are passed.

**Comment by jasonpet** [comment]
@jthomas - this is already supported.  Guess I forgot to update the docs.  The new parameter is called `iamApiKey`.

**Comment by jthomas** [comment]
wooohoo - I was looking in the wrong bit of the code. This is excellent. Can you update the docs or should I?

**Comment by jasonpet** [comment]
I will.

**Comment by csantanapr** [comment]
To clarify the trigger provider Nodejs App uses Basic Auth and this is in this Apache Repo.

For the actions supporting IBM IAM is located in a different repo not Apache, look at the IBM repo here https://github.com/ibm-functions/package-cloudant/blob/master/packages/database-actions/create-query-index.js#L47

**Comment by jasonpet** [comment]
This repo supports IAM and Basic Auth Cloudant service instances for the Cloudant database you are listening to changes on.

**Comment by jasonpet** [comment]
Closing since we have support and now documentation for this.
