### ISSUE TITLE
Support for Trigger filters

### ISSUE THREAD

**Issue by johnsolm** [apache/incubator-openwhisk-package-cloudant#55]
Maybe the CouchDB / Cloudant Design filter function for change feed can be utilized to specify desired filter function. Filter function can also take query parameter(s), which makes it easier to do more dynamic filtering "on demand"...

Filter functions

https://docs.cloudant.com/design_documents.html#filter-functions

Query parameters:
https://docs.cloudant.com/cloudant_query.html#query-parameters

Filter function with query parameter:

GET /$DATABASE/_changes?filter=$DESIGN_ID/$FILTER_FUNCTION&status=new

Filter function described in CouchDB The Definitive Guide

http://guide.couchdb.org/draft/notifications.html

CouchDB on filter functions with query parameter sample:

http://couchdb.readthedocs.io/en/latest/couchapp/ddocs.html#filterfun

So e.g. when creating OpenWhisk trigger, a "filter" parameter could specify the filter function:

wsk -v trigger create myTrigger --feed /org_space/cloudantPackage/changes --param dbname mydb --param includeDoc true --params filter mailbox/by_status&status=new

**Comment by timwis** [comment]
Yes please! Otherwise my function will be triggered _every time_ any change happens. I only want to know when new records of a certain category are created.

**Comment by csantanapr** [comment]
We should not pass filter name and query parameters in a single string.
The query parameters should be it's own feed action parameter
So the new proposal would be 
```
wsk -v trigger create myTrigger --feed /org_space/cloudantPackage/changes \
 --param dbname mydb --param includeDoc true --params filter mailbox/by_status -p query_param "{\"status\":\"new\"}"
```

cc @jasonpet

**Comment by jasonpet** [comment]
@csantanapr - this is complete

**Comment by csantanapr** [comment]
Awesome !
